[2022-06-27 13:32:39,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-06-27 13:32:39,130] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-04-30T00:00:00+00:00 [queued]>
[2022-06-27 13:32:39,131] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:39,132] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:32:39,132] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:39,165] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-04-30 00:00:00+00:00
[2022-06-27 13:32:39,170] {standard_task_runner.py:52} INFO - Started process 58007 to run task
[2022-06-27 13:32:39,191] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-04-30T00:00:00+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpli2vqscp', '--error-file', '/tmp/tmp2zd0u4jy']
[2022-06-27 13:32:39,192] {standard_task_runner.py:80} INFO - Job 612: Subtask model_A
[2022-06-27 13:32:39,285] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-04-30T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:32:39,444] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-30T00:00:00+00:00
[2022-06-27 13:32:39,447] {python.py:173} INFO - Done. Returned value was: 4
[2022-06-27 13:32:39,515] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220430T000000, start_date=20220627T133239, end_date=20220627T133239
[2022-06-27 13:32:39,602] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:32:39,660] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
