[2022-06-27 13:31:44,870] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_C scheduled__2022-03-14T00:00:00+00:00 [queued]>
[2022-06-27 13:31:44,964] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_C scheduled__2022-03-14T00:00:00+00:00 [queued]>
[2022-06-27 13:31:44,967] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:44,972] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:44,975] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:45,047] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_C> on 2022-03-14 00:00:00+00:00
[2022-06-27 13:31:45,053] {standard_task_runner.py:52} INFO - Started process 57417 to run task
[2022-06-27 13:31:45,084] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_C', 'scheduled__2022-03-14T00:00:00+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpyf05byit', '--error-file', '/tmp/tmpvkm175s_']
[2022-06-27 13:31:45,091] {standard_task_runner.py:80} INFO - Job 361: Subtask model_C
[2022-06-27 13:31:45,268] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_C scheduled__2022-03-14T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:45,639] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_C
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T00:00:00+00:00
[2022-06-27 13:31:45,643] {python.py:173} INFO - Done. Returned value was: 8
[2022-06-27 13:31:45,798] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_C, execution_date=20220314T000000, start_date=20220627T133144, end_date=20220627T133145
[2022-06-27 13:31:46,026] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:46,220] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
