[2022-06-27 13:31:58,224] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-03-22T00:00:00+00:00 [queued]>
[2022-06-27 13:31:58,244] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-03-22T00:00:00+00:00 [queued]>
[2022-06-27 13:31:58,248] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:58,252] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:58,253] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:58,295] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-03-22 00:00:00+00:00
[2022-06-27 13:31:58,310] {standard_task_runner.py:52} INFO - Started process 57548 to run task
[2022-06-27 13:31:58,323] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-03-22T00:00:00+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpcvfirpx7', '--error-file', '/tmp/tmp3qufas54']
[2022-06-27 13:31:58,334] {standard_task_runner.py:80} INFO - Job 417: Subtask model_A
[2022-06-27 13:31:58,521] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-03-22T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:58,732] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-03-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-22T00:00:00+00:00
[2022-06-27 13:31:58,734] {python.py:173} INFO - Done. Returned value was: 7
[2022-06-27 13:31:58,909] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220322T000000, start_date=20220627T133158, end_date=20220627T133158
[2022-06-27 13:31:58,988] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:59,131] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
