[2022-06-27 13:32:24,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-06-27 13:32:24,306] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-06-27 13:32:24,314] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:24,315] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:32:24,317] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:24,403] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-04-17 00:00:00+00:00
[2022-06-27 13:32:24,430] {standard_task_runner.py:52} INFO - Started process 57850 to run task
[2022-06-27 13:32:24,444] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-04-17T00:00:00+00:00', '--job-id', '543', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpfy23qbzt', '--error-file', '/tmp/tmpgzz9ob43']
[2022-06-27 13:32:24,459] {standard_task_runner.py:80} INFO - Job 543: Subtask model_A
[2022-06-27 13:32:24,648] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-04-17T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:32:24,908] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-17T00:00:00+00:00
[2022-06-27 13:32:24,910] {python.py:173} INFO - Done. Returned value was: 1
[2022-06-27 13:32:25,024] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220417T000000, start_date=20220627T133224, end_date=20220627T133225
[2022-06-27 13:32:25,115] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:32:25,221] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
