[2022-06-27 13:31:45,918] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-06-27 13:31:45,977] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-06-27 13:31:45,978] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:45,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:45,980] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:46,141] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-03-16 00:00:00+00:00
[2022-06-27 13:31:46,150] {standard_task_runner.py:52} INFO - Started process 57433 to run task
[2022-06-27 13:31:46,223] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-03-16T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpw43zi9u0', '--error-file', '/tmp/tmps5c6k9qe']
[2022-06-27 13:31:46,260] {standard_task_runner.py:80} INFO - Job 367: Subtask model_A
[2022-06-27 13:31:46,639] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-03-16T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:47,099] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-16T00:00:00+00:00
[2022-06-27 13:31:47,115] {python.py:173} INFO - Done. Returned value was: 5
[2022-06-27 13:31:47,341] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220316T000000, start_date=20220627T133145, end_date=20220627T133147
[2022-06-27 13:31:47,454] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:47,558] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
