[2022-06-27 13:32:41,815] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-05-06T00:00:00+00:00 [queued]>
[2022-06-27 13:32:41,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-05-06T00:00:00+00:00 [queued]>
[2022-06-27 13:32:41,836] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:41,837] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:32:41,838] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:32:41,852] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-05-06 00:00:00+00:00
[2022-06-27 13:32:41,860] {standard_task_runner.py:52} INFO - Started process 58043 to run task
[2022-06-27 13:32:41,869] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-05-06T00:00:00+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpo0b6tccd', '--error-file', '/tmp/tmp1m8v2e36']
[2022-06-27 13:32:41,876] {standard_task_runner.py:80} INFO - Job 633: Subtask model_A
[2022-06-27 13:32:42,035] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-05-06T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:32:42,237] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-05-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-06T00:00:00+00:00
[2022-06-27 13:32:42,246] {python.py:173} INFO - Done. Returned value was: 2
[2022-06-27 13:32:42,296] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220506T000000, start_date=20220627T133241, end_date=20220627T133242
[2022-06-27 13:32:42,384] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:32:42,452] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
