[2022-06-27 13:31:05,746] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-02-03T00:00:00+00:00 [queued]>
[2022-06-27 13:31:05,761] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag1.model_A scheduled__2022-02-03T00:00:00+00:00 [queued]>
[2022-06-27 13:31:05,762] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:05,765] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-27 13:31:05,765] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:31:05,805] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): model_A> on 2022-02-03 00:00:00+00:00
[2022-06-27 13:31:05,818] {standard_task_runner.py:52} INFO - Started process 57007 to run task
[2022-06-27 13:31:05,839] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'model_A', 'scheduled__2022-02-03T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpfaip60x3', '--error-file', '/tmp/tmpemmtj0dt']
[2022-06-27 13:31:05,841] {standard_task_runner.py:80} INFO - Job 182: Subtask model_A
[2022-06-27 13:31:05,974] {task_command.py:370} INFO - Running <TaskInstance: dag1.model_A scheduled__2022-02-03T00:00:00+00:00 [running]> on host 43f8d36cfb0f
[2022-06-27 13:31:06,201] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=model_A
AIRFLOW_CTX_EXECUTION_DATE=2022-02-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-03T00:00:00+00:00
[2022-06-27 13:31:06,203] {python.py:173} INFO - Done. Returned value was: 9
[2022-06-27 13:31:06,284] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=model_A, execution_date=20220203T000000, start_date=20220627T133105, end_date=20220627T133106
[2022-06-27 13:31:06,338] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:31:06,461] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
